from pycontrol_homecage.dialogs.calibrate_dialog        import CalibrationDialog
from pycontrol_homecage.dialogs.box_conn_dialog         import BoxConnectionDialog
from pycontrol_homecage.dialogs.login_dialog            import LoginDialog
from pycontrol_homecage.dialogs.are_you_sure_dialog     import AreYouSureDialog
from pycontrol_homecage.dialogs.add_user_dialog         import AddUserDialog
from pycontrol_homecage.dialogs.configure_box_dialog    import ConfigureBoxDialog
from pycontrol_homecage.dialogs.mouse_summary_dialog    import MouseSummaryDialog
from pycontrol_homecage.dialogs.cage_summary_dialog     import CageSummaryDialog
from pycontrol_homecage.dialogs.direct_pyboard_dialog   import DirectPyboardDialog
from pycontrol_homecage.dialogs.information_dialog      import InformationDialog
from pycontrol_homecage.dialogs.add_mouse_dialog        import AddMouseDialog