from .calibrate_dialog        import CalibrationDialog
from .box_conn_dialog         import BoxConnectionDialog
from .login_dialog            import LoginDialog
from .are_you_sure_dialog     import AreYouSureDialog
from .add_user_dialog         import AddUserDialog
from .configure_box_dialog    import ConfigureBoxDialog
from .mouse_summary_dialog    import MouseSummaryDialog
from .cage_summary_dialog     import CageSummaryDialog
from .direct_pyboard_dialog   import DirectPyboardDialog
from .information_dialog      import InformationDialog
from .add_mouse_dialog        import AddMouseDialog
from .direct_protocol_dialog  import DirectProtocolDialog
from .new_experiment_menu     import NewExperimentDialog